// Mock data matching the wedding invitation schema
export const mockInvitations = {
  elegant: {
    slug: "sarah-and-john-wedding",
    title: "The Wedding of Sarah & John",
    language: "en" as "en" | "id",
    theme_id: 3,
    published: true,
    bride_callname: "Sarah",
    bride_fullname: "Sarah Elizabeth Smith",
    bride_info_1: "Daughter of Mr. & Mrs. Robert Smith",
    bride_info_2: "The eldest daughter",
    bride_info_3: "@sarahelizabeth",
    groom_callname: "John",
    groom_fullname: "John Michael Anderson",
    groom_info_1: "Son of Mr. & Mrs. William Anderson",
    groom_info_2: "The second son",
    groom_info_3: "@johnmichael",
    events: [
      {
        type: "ceremony",
        title: "Wedding Ceremony",
        start_time: "2026-06-15T14:00",
        end_time: "2026-06-15T15:30",
        location_name: "St. Mary's Cathedral",
        location_address: "123 Church Street, Downtown, New York, NY 10001",
        map_url: "https://maps.google.com/?q=St.+Mary's+Cathedral+New+York",
      },
      {
        type: "reception",
        title: "Wedding Reception",
        start_time: "2026-06-15T18:00",
        end_time: "2026-06-15T23:00",
        location_name: "Grand Ballroom Hotel",
        location_address: "456 Grand Avenue, Manhattan, New York, NY 10002",
        map_url: "https://maps.google.com/?q=Grand+Ballroom+Hotel+New+York",
      },
    ],
    gifts: [
      {
        type: "bank",
        provider: "Bank of America",
        account_name: "Sarah & John Wedding",
        account_number: "1234567890",
      },
      {
        type: "ewallet",
        provider: "PayPal",
        account_name: "sarah.john.wedding@email.com",
        account_number: "sarah.john.wedding@email.com",
      },
    ],
    livestream_platform: "youtube",
    livestream_url: "https://youtube.com/live/sample-stream-id",
    livestream_event_date: "2026-06-15",
    livestream_start_time: "14:00",
    livestream_is_active: true,
    audio_id: 1,
    autoplay: true,
    loop: true,
    is_active: true,
  },
  indonesian: {
    slug: "pernikahan-andi-dan-siti",
    title: "Pernikahan Andi & Siti",
    language: "id" as "en" | "id",
    theme_id: 3,
    published: false,
    bride_callname: "Siti",
    bride_fullname: "Siti Nurhaliza Putri",
    bride_info_1: "Putri dari Bapak Hasan & Ibu Fatimah",
    bride_info_2: "Putri pertama",
    bride_info_3: "@sitinurhaliza",
    groom_callname: "Andi",
    groom_fullname: "Andi Rahman Hakim",
    groom_info_1: "Putra dari Bapak Ahmad & Ibu Sari",
    groom_info_2: "Putra kedua",
    groom_info_3: "@andirahman",
    events: [
      {
        type: "ceremony",
        title: "Akad Nikah",
        start_time: "2026-07-20T08:00",
        end_time: "2026-07-20T10:00",
        location_name: "Masjid Al-Ikhlas",
        location_address:
          "Jl. Mawar No. 123, Jakarta Selatan, DKI Jakarta 12345",
        map_url: "https://maps.google.com/?q=Masjid+Al-Ikhlas+Jakarta",
      },
      {
        type: "reception",
        title: "Resepsi Pernikahan",
        start_time: "2026-07-20T18:00",
        end_time: "2026-07-20T21:00",
        location_name: "Gedung Serbaguna",
        location_address:
          "Jl. Melati No. 456, Jakarta Selatan, DKI Jakarta 12346",
        map_url: "https://maps.google.com/?q=Gedung+Serbaguna+Jakarta",
      },
    ],
    gifts: [
      {
        type: "bank",
        provider: "Bank Mandiri",
        account_name: "Andi Rahman Hakim",
        account_number: "1234567890123",
      },
      {
        type: "ewallet",
        provider: "GoPay",
        account_name: "Andi Rahman",
        account_number: "081234567890",
      },
      {
        type: "ewallet",
        provider: "OVO",
        account_name: "Andi Rahman",
        account_number: "081234567890",
      },
    ],
    livestream_platform: "instagram",
    livestream_url: "https://instagram.com/andirahman/live",
    livestream_event_date: "2026-07-20",
    livestream_start_time: "08:00",
    livestream_is_active: true,
    audio_id: 1,
    autoplay: true,
    loop: true,
    is_active: true,
  },
  modern: {
    slug: "alex-and-emma-2026",
    title: "Alex & Emma Forever",
    language: "en" as "en" | "id",
    theme_id: 3,
    published: true,
    bride_callname: "Emma",
    bride_fullname: "Emma Rose Johnson",
    bride_info_1: "Daughter of Mr. & Mrs. David Johnson",
    bride_info_2: "Software Engineer",
    bride_info_3: "@emmarose",
    groom_callname: "Alex",
    groom_fullname: "Alexander James Miller",
    groom_info_1: "Son of Mr. & Mrs. James Miller",
    groom_info_2: "Product Designer",
    groom_info_3: "@alexjames",
    events: [
      {
        type: "ceremony",
        title: "Garden Wedding Ceremony",
        start_time: "2026-09-10T16:00",
        end_time: "2026-09-10T17:00",
        location_name: "Botanical Gardens",
        location_address: "789 Green Park Avenue, San Francisco, CA 94102",
        map_url: "https://maps.google.com/?q=Botanical+Gardens+San+Francisco",
      },
      {
        type: "reception",
        title: "Rooftop Reception Party",
        start_time: "2026-09-10T19:00",
        end_time: "2026-09-11T01:00",
        location_name: "Sky Lounge & Bar",
        location_address:
          "321 High Street, 25th Floor, San Francisco, CA 94103",
        map_url: "https://maps.google.com/?q=Sky+Lounge+Bar+San+Francisco",
      },
      {
        type: "other",
        title: "Brunch with Friends",
        start_time: "2026-09-11T10:00",
        end_time: "2026-09-11T13:00",
        location_name: "Sunny Side Cafe",
        location_address: "654 Beach Road, San Francisco, CA 94104",
        map_url: "https://maps.google.com/?q=Sunny+Side+Cafe+San+Francisco",
      },
    ],
    gifts: [
      {
        type: "bank",
        provider: "Chase Bank",
        account_name: "Alex & Emma Miller-Johnson",
        account_number: "9876543210",
      },
      {
        type: "ewallet",
        provider: "Venmo",
        account_name: "@alexandemma",
        account_number: "@alexandemma",
      },
      {
        type: "giftRegistry",
        provider: "Amazon Registry",
        account_name: "Alex & Emma Wedding Registry",
        account_number: "https://amazon.com/wedding/registry/alexemma2026",
      },
    ],
    livestream_platform: "zoom",
    livestream_url: "https://zoom.us/j/1234567890",
    livestream_event_date: "2026-09-10",
    livestream_start_time: "16:00",
    livestream_is_active: true,
    audio_id: null,
    autoplay: false,
    loop: true,
    is_active: true,
  },
  simple: {
    slug: "simple-wedding-test",
    title: "Simple Wedding",
    language: "en" as "en" | "id",
    theme_id: 3,
    published: false,
    bride_callname: "Jane",
    bride_fullname: "Jane Marie Doe",
    bride_info_1: "Daughter of John & Mary Doe",
    bride_info_2: "",
    bride_info_3: "",
    groom_callname: "Jack",
    groom_fullname: "Jack William Smith",
    groom_info_1: "Son of William & Linda Smith",
    groom_info_2: "",
    groom_info_3: "",
    events: [
      {
        type: "ceremony",
        title: "Wedding Ceremony & Reception",
        start_time: "2026-08-15T15:00",
        end_time: "2026-08-15T20:00",
        location_name: "Community Hall",
        location_address: "100 Main Street, Springfield, IL 62701",
        map_url: "https://maps.google.com/?q=Community+Hall+Springfield",
      },
    ],
    gifts: [],
    livestream_platform: null,
    livestream_url: "",
    livestream_event_date: "",
    livestream_start_time: "",
    livestream_is_active: false,
    audio_id: null,
    autoplay: true,
    loop: true,
    is_active: true,
  },
};

// Get list of mock invitation names
export const getMockInvitationNames = () => Object.keys(mockInvitations);

// Get mock invitation by name
export const getMockInvitation = (name: string) => {
  return mockInvitations[name as keyof typeof mockInvitations];
};
